---
- name: Install the tkn cli
  ansible.builtin.shell: |
    curl -LO https://github.com/tektoncd/cli/releases/download/v0.11.0/tkn_0.11.0_Linux_x86_64.tar.gz
    tar xvzf tkn_0.11.0_Linux_x86_64.tar.gz -C /usr/local/bin/
- name: Run the CI pipeline
  ansible.builtin.shell: |
     tkn pipeline start operator-ci-pipeline \
       --param git_repo_url=git@github.com:redhat-openshift-ecosystem/operator-pipelines-test.git \
       --param git_branch=main \
       --param bundle_path=operators/kogito-operator/1.6.0-ok \
       --param env=dev \
       --param registry=quay.io \
       --param image_namespace=redhat-isv \
       --workspace name=pipeline,volumeClaimTemplateFile=../templates/workspace-template.yml \
       --workspace name=kubeconfig,secret=kubeconfig \
       --workspace name=registry-credentials,secret=registry-dockerconfig-secret \
       --workspace name=pyxis-api-key,secret=pyxis-api-secret \
       --showlog