---
- name: Deploy operator-pipeline {{ env }} instance
  hosts: operator-pipeline-{{ env }}
  vars_files:
    - ../vaults/{{ (custom-name) if (custom-name) is defined else (env) }}/ocp-token.yml
    - ../vaults/{{ env }}/secret-vars.yml
  roles:
    - deployment
  environment:
    K8S_AUTH_API_KEY: '{{ ocp_token }}'
    K8S_AUTH_HOST: '{{ ocp_host }}'
