---
name: E2E-CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - ISV-1108
  workflow_dispatch:

jobs:
  deploy-e2e-env:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install --user openshift
      - name: Install pipelines
        run: |
          cd ansible
          echo {{secrets.VAULT_PASSWORD}} > vault-password
          chmod +x init-custom-env.sh
          bash init-custom-env.sh marcin-playground qa vault-password
