---
name: E2E-CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - ISV-1108
  workflow_dispatch:

jobs:
  install-tkn:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: install-tkn
        run: |
          curl -LO https://github.com/tektoncd/cli/releases/download/v0.11.0/tkn_0.11.0_Linux_x86_64.tar.gz
          tar xvzf tkn_0.11.0_Linux_x86_64.tar.gz -C /usr/local/bin/

  run-e2e:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install --user openshift
      - name: Deploy dev environment
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/e2e.yml
          directory: ./ansible
          requirements: playbooks/requirements.yml
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory inventory/operator-pipeline
            --verbose

#  deploy-e2e-dev:
#    runs-on: ubuntu-latest
#    environment:
#      name: dev
#    steps:
#      - uses: actions/checkout@v1
#      - name: Install dependencies
#        run: |
#          pip install --user openshift
#      - name: Deploy dev environment
#        uses: dawidd6/action-ansible-playbook@v2
#        with:
#          playbook: playbooks/deploy.yml
#          directory: ./ansible
#          requirements: playbooks/requirements.yml
#          vault_password: ${{secrets.VAULT_PASSWORD}}
#          options: |
#            --inventory inventory/operator-pipeline
#            --extra-vars env=dev
#            --extra-vars custom_var_location=e2e
#            --extra-vars namespace=marcin-playground
#            --verbose
