---
name: E2E-CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - ISV-1108-2
  workflow_dispatch:
jobs:
  run-e2e:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment
        run: |
          # Install dependencies
          pip install --user openshift

          # Install tkn cli
          curl -LO https://github.com/tektoncd/cli/releases/download/v0.11.0/tkn_0.11.0_Linux_x86_64.tar.gz
          tar xvzf tkn_0.11.0_Linux_x86_64.tar.gz -C /usr/local/bin/

          # Prepare Kubeconfig
          mkdir $HOME/.kube
          cat <<EOF > $HOME/.kube/config
          ${{ secrets.KUBECONFIG }}
          EOF

          # Prepare vault password
          echo ${{ secrets.VAULT_PASSWORD }} > ansible/vault-password
      - name: Deploy e2e environment
        run: |
          # TODO: project name
          oc new-project test-e2e || true
          pushd ansible
          bash init-custom-env.sh test-e2e qa vault-password
          popd
      - name: Run CI pipeline
        run: |
          tkn pipeline -n test-e2e start operator-ci-pipeline \
            --param git_repo_url=git@github.com:redhat-openshift-ecosystem/operator-pipelines-test.git \
            --param git_branch=main \
            --param bundle_path=operators/kogito-operator/1.6.0-ok \
            --param env=dev \
            --param registry=quay.io \
            --param image_namespace=redhat-isv \
            --workspace name=pipeline,volumeClaimTemplateFile=templates/workspace-template.yml \
            --workspace name=kubeconfig,secret=kubeconfig \
            --workspace name=registry-credentials,secret=registry-dockerconfig-secret \
            --workspace name=pyxis-api-key,secret=pyxis-api-secret \
            --showlog
      - name: Check if pipeline passed
        run: |
          SUCCEEDED=$(oc get pr e2e-pipelinerun -o jsonpath={'.status.conditions[].status'})
          if [[ "$SUCCEEDED" != "True" ]]; then
            exit 0
          fi
      - name: Cleanup
        if: always()
        run: |
          oc delete project test-e2e

